services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - ./quasar-project/src:/app/src
      - ./quasar-project/public:/app/public
      - ./quasar-project/quasar.config.js:/app/quasar.config.js
      - ./quasar-project/package.json:/app/package.json
      - ./quasar-project/package-lock.json:/app/package-lock.json
    ports:
      - "9000:9000"
    container_name: quasar-frontend

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.symfony
    volumes:
      - ./api-backend:/app
    ports:
      - "8000:8000"
    env_file:
      - api-backend/.env
    command: php -S 0.0.0.0:8000 -t public public/index.php
    depends_on:
      - database
    container_name: api_backend

  database:
    image: mariadb:11.8.2
    environment:
      MYSQL_ROOT_PASSWORD: "YourPassword123"
      MYSQL_DATABASE: "GreenITScan"
    ports:
      - "3307:3306"
    volumes:
      - GreenITScan_mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "bash", "-c", "</dev/tcp/127.0.0.1/3306"]
      interval: 5s
      timeout: 5s
      retries: 10
    container_name: mariadb_database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "YourPassword123"
    ports:
      - "8080:80"
    depends_on:
      - database
    container_name: phpmyadmin

  cypress:
    image: cypress/included:12.17.3
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend:9000
    working_dir: /e2e
    volumes:
      - ./quasar-project:/e2e
    command: npx cypress run
    
volumes:
  GreenITScan_mariadb_data: